"""Add initial admin user

Revision ID: 041bbe1d824a
Revises: 74b77d0df6e8
Create Date: 2025-10-21 22:09:38.117886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041bbe1d824a'
down_revision: Union[str, Sequence[str], None] = '74b77d0df6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from uuid import uuid4
    from datetime import datetime, timezone
    from app.infrastructure.security.argon2_password_hasher import Argon2PasswordHasher
    from app.users.domain.value_objects import Rol

    password_hasher = Argon2PasswordHasher()
    admin_password_hashed = password_hasher.hash("Surfear1+")

    op.execute(
        f"""
        INSERT INTO usuarios (id, email, contrasena_hasheada, nombre, apellidos, numero_telefono, rol, esta_activo, email_verificado, aprobado_por_admin, fecha_creacion, fecha_actualizacion)
        VALUES (
            '{uuid4()}',
            'admin@example.com',
            '{admin_password_hashed}',
            'Miguel',
            'Vigo',
            '600533729',
            '{Rol.ADMIN.value}',
            TRUE,
            TRUE,
            TRUE,
            '{datetime.now(timezone.utc).isoformat()}',
            '{datetime.now(timezone.utc).isoformat()}'
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
