"""Initial migration
Revision ID: 32b8215a3322
Revises:
Create Date: 2025-11-03 12:28:40.295635
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '32b8215a3322'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporadacuotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_temporada', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_temporada')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contrasena_hasheada', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('numero_telefono', sa.String(length=20), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'USUARIO', name='rol'), nullable=False),
    sa.Column('apodo', sa.String(length=50), nullable=True),
    sa.Column('url_avatar', sa.String(), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('email_verificado', sa.Boolean(), nullable=False),
    sa.Column('aprobado_por_admin', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_telefono')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('tipocuotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Enum('ALTA', 'SOCIO', name='nombretipocuota_enum'), nullable=False),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadacuotas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('hash_token', sa.String(), nullable=False),
    sa.Column('tipo_token', sa.Enum('VERIFICACION_EMAIL', 'RESETEO_CONTRASENA', 'REFRESH_TOKEN', name='tipotoken'), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('es_valido', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_hash_token'), 'tokens', ['hash_token'], unique=True)
    op.create_index(op.f('ix_tokens_usuario_id'), 'tokens', ['usuario_id'], unique=False)
    op.create_table('cuotas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo_de_cuota_id', sa.Integer(), nullable=False),
    sa.Column('importe_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_pago', sa.String(length=50), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metodo_pago', sa.Enum('STRIPE', 'EFECTIVO', 'TRANSFERENCIA_MANUAL', name='tipo_metodo_pago'), nullable=True),
    sa.Column('id_transaccion_externa', sa.String(length=255), nullable=True),
    sa.Column('notas_admin', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tipo_de_cuota_id'], ['tipocuotas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_transaccion_externa')
    )
    op.create_table('prendas',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nombre', sa.String(length=100), nullable=False),
        sa.Column('descripcion', sa.Text(), nullable=True),
        sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('imagen_url', sa.String(length=255), nullable=True),
        sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nombre')
    )
    op.create_table('varianteprendas',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('prenda_id', sa.UUID(), nullable=False),
        sa.Column('genero', sa.Enum('HOMBRE', 'MUJER', 'UNISEX', name='genero_prenda_enum'), nullable=False),
        sa.Column('talla', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', name='talla_prenda_enum'), nullable=False),
        sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['prenda_id'], ['prendas.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### Manually added trigger logic ###
    op.execute("""
        CREATE OR REPLACE FUNCTION check_unique_user_season_fee()
        RETURNS TRIGGER AS '
        DECLARE
            v_temporada_id INT;
            fee_count INT;
        BEGIN
            SELECT temporada_id INTO v_temporada_id
            FROM tipocuotas
            WHERE id = NEW.tipo_de_cuota_id;
            IF NOT FOUND THEN
                RETURN NEW;
            END IF;
            SELECT COUNT(*) INTO fee_count
            FROM cuotas c
            JOIN tipocuotas tc ON c.tipo_de_cuota_id = tc.id
            WHERE c.usuario_id = NEW.usuario_id
            AND tc.temporada_id = v_temporada_id;
            IF fee_count > 0 THEN
                RAISE EXCEPTION ''El usuario ya tiene una cuota asignada para esta temporada.'';
            END IF;
            RETURN NEW;
        END;
        ' LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_check_unique_user_season_fee
        BEFORE INSERT ON cuotas
        FOR EACH ROW
        EXECUTE FUNCTION check_unique_user_season_fee();
    """)
    # ### end Alembic commands ###
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_check_unique_user_season_fee ON cuotas;")
    op.execute("DROP FUNCTION IF EXISTS check_unique_user_season_fee();")
    op.drop_table('varianteprendas')
    op.drop_table('prendas')
    op.drop_table('cuotas')
    op.drop_index(op.f('ix_tokens_usuario_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_hash_token'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_table('tipocuotas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('temporadacuotas')
    # ### end Alembic commands ###
