"""Initial migration

Revision ID: 74b77d0df6e8
Revises: 
Create Date: 2025-10-21 22:05:53.911061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b77d0df6e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('hash_token', sa.String(), nullable=False),
    sa.Column('tipo_token', sa.Enum('VERIFICACION_EMAIL', 'RESETEO_CONTRASENA', 'REFRESH_TOKEN', name='tipotoken'), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('es_valido', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_hash_token'), 'tokens', ['hash_token'], unique=True)
    op.create_index(op.f('ix_tokens_usuario_id'), 'tokens', ['usuario_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contrasena_hasheada', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('numero_telefono', sa.String(length=20), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'USUARIO', name='rol'), nullable=False),
    sa.Column('apodo', sa.String(length=50), nullable=True),
    sa.Column('url_avatar', sa.String(), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('email_verificado', sa.Boolean(), nullable=False),
    sa.Column('aprobado_por_admin', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_telefono')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tokens_usuario_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_hash_token'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
