"""Add cuotas tables

Revision ID: 9bae539e3960
Revises: c671f93560b6
Create Date: 2025-10-28 15:54:53.742396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bae539e3960'
down_revision: Union[str, Sequence[str], None] = 'c671f93560b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporadacuotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_temporada', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_temporada')
    )
    op.create_table('tipocuotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadacuotas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuotas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo_de_cuota_id', sa.Integer(), nullable=False),
    sa.Column('importe_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_pago', sa.String(length=50), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('id_transaccion_externa', sa.String(length=255), nullable=True),
    sa.Column('notas_admin', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tipo_de_cuota_id'], ['tipocuotas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_transaccion_externa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuotas')
    op.drop_table('tipocuotas')
    op.drop_table('temporadacuotas')
    # ### end Alembic commands ###
